// <auto-generated />
namespace BE_U2_W3_Pizzeria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AggiuntoQuantitaInProdotti : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AggiuntoQuantitaInProdotti));
        
        string IMigrationMetadata.Id
        {
            get { return "202403141722516_AggiuntoQuantitaInProdotti"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
